[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mt4a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.102.0",
    "bcrypt>=5.0.0",
    "fastapi>=0.136.1",
    "mysql-connector-python>=9.7.0",
    "pyjwt>=2.10.0",
    "python-dotenv>=1.2.2",
    "sqlmodel>=0.0.38",
    "rank-bm25>=0.2.2",
    "python-docx>=1.2.0",
    "ollama>=0.6.2",
    "python-multipart>=0.0.29",
    "llama-index-embeddings-dashscope==0.1.4",
    "llama-index-readers-file==0.1.33",
    "llama-index-postprocessor-dashscope-rerank-custom==0.1.0",
    "faiss-cpu==1.8.0.post1",
    "dashscope==1.20.4",
    "llama-index-core==0.10.67",
    "llama-index-vector-stores-faiss==0.1.2",
    "uvicorn>=0.47.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]
